### ISSUE TITLE
Seminário 1: revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [mglnb/GoDinner#1]
O setor gastronômico esteve em constante crescimento nestes últimos anos. O hábito de se alimentar fora tem sido cada vez mais incorporado ao dia a dia dos brasileiros, e com o crescimento, os clientes começam a ficar mais exigentes. Segundo ao blog “Gestao De Restaurantes”, entre as reclamações mais comuns dos clientes, existe a desatenção dos garçons, a demora na chegada de pratos e a falta de informação sobre o cardápio. Visando estas reclamações, e varias outras necessidades, surgiu o projeto RealTaste que irá conter estas informações para o cliente, e ao mesmo tempo permitir que o estabelecimento aproveite o sistema para aumentar suas vendas.

1) Corrigir a justificativa/motivação acima
2) Quais as diferenças dos outros sistemas similares?
3) Os itens do cronograma devem ser exatamente iguais aos “Objetivos Específicos”
4) Rever nome do sistema, pois não mostra o que o sistema faz
5) Inserir frase introdutória nos Objetivos Específicos, requisitos funcionais e não-funcionais
6) Funcionalidades bem definidas
7)

**Comment by mglnb** [comment]
- [X] **Corrigir a justificativa/motivação acima**
 Corrigido.

- [ ] **Quais as diferenças dos outros sistemas similares?**

- [X] **Os itens do cronograma devem ser exatamente iguais aos “Objetivos Específicos”**
  Separei alguns termos na parte de objetivos e deixei igual no cronograma.
- [X] **Rever nome do sistema, pois não mostra o que o sistema faz**
  Realmente, RealTaste estava no tema de culinária e não de pedidos.  Mudei para GoDinner, como uma forma de ser um aplicativo a ser usado sempre que a pessoa queira sair para comer.
- [ ] **Inserir frase introdutória nos Objetivos Específicos, requisitos funcionais e não-funcionais**
