### ISSUE TITLE
Seminario2-revEdecio

### ISSUE THREAD

**Issue by edeciofernando** [mglnb/GoDinner#16]
- Muito bom!  Trabalho e atividades desenvolvidas de acordo com o esperado para o TCC.

Sugestões:

- [x] Ampliar / reorganizar apresentação do modelo E-R na Wiki.

- [x] Adicionar subtítulo para comparativo com sistemas relacionados (na Wiki, ficou junto com casos de uso).

**Comment by mglnb** [comment]
Feito
