### ISSUE TITLE
Seminario1-revEdécio

### ISSUE THREAD

**Issue by edeciofernando** [mglnb/GoDinner#2]
Sugestões:

- [x] Sistema grande, cuidado com o cumprimento do cronograma

- [x] Pensar / implementar recursos visando obter retorno financeiro com o sistema

- [x] Avaliar funcionalidades (como avaliação de pratos) que podem ser benéficas, mas ao mesmo tempo, preocupantes para os restaurantes que irão utilizar a plataforma

**Comment by mglnb** [comment]
- [X] **Sistema grande, cuidado com o cumprimento do cronograma**
  Ok!
- [ ] **Pensar / implementar recursos visando obter retorno financeiro com o sistema**

- [X] **Avaliar funcionalidades (como avaliação de pratos) que podem ser benéficas, mas ao mesmo tempo, preocupantes para os restaurantes que irão utilizar a plataforma**
  Retirei a funcionalidade de avaliação de pratos, deixando apenas a avaliação do restaurante.
Através da avaliação do restaurante, terá informações do pedido do cliente, assim quem ver, verá o que o cliente comeu, e sua avaliação geral do restaurante.
