### ISSUE TITLE
Seminario3-revGladimir  

### ISSUE THREAD

**Issue by gladimircc** [mglnb/GoDinner#20]
- [x] Ajustar texto da Motivação/Justificativa

Sugestão:

...
Visando dirimir estas reclamações, e atender várias outras necessidades, surgiu o projeto GoDinner que irá disponibilizar estas informações do cliente, ao mesmo tempo que permitirá ao estabelecimento a possibilidade de aumentar suas vendas através do uso do sistema.

...

**Comment by mglnb** [comment]
Ok!
